### ISSUE TITLE
Servo control not working

### ISSUE THREAD

**Issue by jerzmerner** [DFRobot/pxt-DFRobot_MaqueenPlus_v20#1]
I can't get a servo to move at all.

**Comment by ostaquet** [comment]
Be sure you initialised the I2C bus through the init block and use Maqueen Plus V2 (it could have some incompatibilities with other Maqueen versions)

**Comment by mrewak** [comment]
I have the same issue. There is no block to control servo in this library. Using the block from previous version (https://github.com/DFRobot/pxt-DFRobot-Maqueenplus/blob/master/maqueenplus.ts) doesn't help.
Tested with the Init block from this and previous library.
