### ISSUE TITLE
remove Ws2812 part of extension - is it possible

### ISSUE THREAD

**Issue by dsssssssss9** [DFRobot/pxt-DFRobot_MaqueenPlus_v20#4]
Hi

I have a project that uses an led matrix to display information - unfortunately  the WS2812 part of MaqueenPlus_v20  extension is incompatible so i can't have both extensions installed at the same time 
 .
I need to use the LED matrix extension so i am wondering if it would be possible to get a version of the MaqueenPlus_v20 extension that DOES NOT have the WS2812  ? That way i could still use the features of the Maqueen plus ( minus the 4 WS2812 LED which are not required ) along with the LED matrix extension?

Regards

Jason

**Comment by tangjie133** [comment]
Sorry, this cannot be deleted for the time being
